version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: onlineshop_db
    environment:
      POSTGRES_DB: onlineshop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 21211488
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: onlineshop_backend
    command: sh -c "python manage.py migrate && python create_superuser.py && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_NAME=onlineshop_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=21211488
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_PHONE_NUMBER=1234567890
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  media_volume:

